// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

#include "proto/message.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace proto {
PROTOBUF_CONSTEXPR Message::Message(
    ::_pbi::ConstantInitialized)
  : _oneof_case_{}{}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace proto
static ::_pb::Metadata file_level_metadata_proto_2fmessage_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fmessage_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fmessage_2eproto = nullptr;

const uint32_t TableStruct_proto_2fmessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::proto::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::proto::Message, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::proto::Message, type_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::proto::Message)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::proto::_Message_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fmessage_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023proto/message.proto\022\005proto\032\027proto/tran"
  "saction.proto\032\022proto/server.proto\032\022proto"
  "/client.proto\032\023proto/storage.proto\032\020prot"
  "o/node.proto\"\376\003\n\007Message\022!\n\003txn\030\001 \001(\0132\022."
  "proto.TransactionH\000\022E\n\032reply_txn_result_"
  "to_client\030\002 \001(\0132\037.proto.ReplyTransaction"
  "ToClientH\000\0227\n\023client_read_request\030\003 \001(\0132"
  "\030.proto.ClientReadRequestH\000\0229\n\024client_re"
  "ad_response\030\004 \001(\0132\031.proto.ClientReadResp"
  "onseH\000\0229\n\024storage_pull_request\030\005 \001(\0132\031.p"
  "roto.StoragePullRequestH\000\022;\n\025storage_pul"
  "l_response\030\006 \001(\0132\032.proto.StoragePullResp"
  "onseH\000\022;\n\025storage_push_response\030\007 \001(\0132\032."
  "proto.StoragePushResponseH\000\022*\n\014raft_requ"
  "est\030\010 \001(\0132\022.proto.RaftRequestH\000\022,\n\rraft_"
  "response\030\t \001(\0132\023.proto.RaftResponseH\000B\006\n"
  "\004typeb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fmessage_2eproto_deps[5] = {
  &::descriptor_table_proto_2fclient_2eproto,
  &::descriptor_table_proto_2fnode_2eproto,
  &::descriptor_table_proto_2fserver_2eproto,
  &::descriptor_table_proto_2fstorage_2eproto,
  &::descriptor_table_proto_2ftransaction_2eproto,
};
static ::_pbi::once_flag descriptor_table_proto_2fmessage_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fmessage_2eproto = {
    false, false, 653, descriptor_table_protodef_proto_2fmessage_2eproto,
    "proto/message.proto",
    &descriptor_table_proto_2fmessage_2eproto_once, descriptor_table_proto_2fmessage_2eproto_deps, 5, 1,
    schemas, file_default_instances, TableStruct_proto_2fmessage_2eproto::offsets,
    file_level_metadata_proto_2fmessage_2eproto, file_level_enum_descriptors_proto_2fmessage_2eproto,
    file_level_service_descriptors_proto_2fmessage_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fmessage_2eproto_getter() {
  return &descriptor_table_proto_2fmessage_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fmessage_2eproto(&descriptor_table_proto_2fmessage_2eproto);
namespace proto {

// ===================================================================

class Message::_Internal {
 public:
  static const ::proto::Transaction& txn(const Message* msg);
  static const ::proto::ReplyTransactionToClient& reply_txn_result_to_client(const Message* msg);
  static const ::proto::ClientReadRequest& client_read_request(const Message* msg);
  static const ::proto::ClientReadResponse& client_read_response(const Message* msg);
  static const ::proto::StoragePullRequest& storage_pull_request(const Message* msg);
  static const ::proto::StoragePullResponse& storage_pull_response(const Message* msg);
  static const ::proto::StoragePushResponse& storage_push_response(const Message* msg);
  static const ::proto::RaftRequest& raft_request(const Message* msg);
  static const ::proto::RaftResponse& raft_response(const Message* msg);
};

const ::proto::Transaction&
Message::_Internal::txn(const Message* msg) {
  return *msg->type_.txn_;
}
const ::proto::ReplyTransactionToClient&
Message::_Internal::reply_txn_result_to_client(const Message* msg) {
  return *msg->type_.reply_txn_result_to_client_;
}
const ::proto::ClientReadRequest&
Message::_Internal::client_read_request(const Message* msg) {
  return *msg->type_.client_read_request_;
}
const ::proto::ClientReadResponse&
Message::_Internal::client_read_response(const Message* msg) {
  return *msg->type_.client_read_response_;
}
const ::proto::StoragePullRequest&
Message::_Internal::storage_pull_request(const Message* msg) {
  return *msg->type_.storage_pull_request_;
}
const ::proto::StoragePullResponse&
Message::_Internal::storage_pull_response(const Message* msg) {
  return *msg->type_.storage_pull_response_;
}
const ::proto::StoragePushResponse&
Message::_Internal::storage_push_response(const Message* msg) {
  return *msg->type_.storage_push_response_;
}
const ::proto::RaftRequest&
Message::_Internal::raft_request(const Message* msg) {
  return *msg->type_.raft_request_;
}
const ::proto::RaftResponse&
Message::_Internal::raft_response(const Message* msg) {
  return *msg->type_.raft_response_;
}
void Message::set_allocated_txn(::proto::Transaction* txn) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (txn) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(txn));
    if (message_arena != submessage_arena) {
      txn = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, txn, submessage_arena);
    }
    set_has_txn();
    type_.txn_ = txn;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.txn)
}
void Message::clear_txn() {
  if (_internal_has_txn()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.txn_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_reply_txn_result_to_client(::proto::ReplyTransactionToClient* reply_txn_result_to_client) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (reply_txn_result_to_client) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(reply_txn_result_to_client));
    if (message_arena != submessage_arena) {
      reply_txn_result_to_client = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reply_txn_result_to_client, submessage_arena);
    }
    set_has_reply_txn_result_to_client();
    type_.reply_txn_result_to_client_ = reply_txn_result_to_client;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.reply_txn_result_to_client)
}
void Message::clear_reply_txn_result_to_client() {
  if (_internal_has_reply_txn_result_to_client()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.reply_txn_result_to_client_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_client_read_request(::proto::ClientReadRequest* client_read_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (client_read_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(client_read_request));
    if (message_arena != submessage_arena) {
      client_read_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, client_read_request, submessage_arena);
    }
    set_has_client_read_request();
    type_.client_read_request_ = client_read_request;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.client_read_request)
}
void Message::clear_client_read_request() {
  if (_internal_has_client_read_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.client_read_request_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_client_read_response(::proto::ClientReadResponse* client_read_response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (client_read_response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(client_read_response));
    if (message_arena != submessage_arena) {
      client_read_response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, client_read_response, submessage_arena);
    }
    set_has_client_read_response();
    type_.client_read_response_ = client_read_response;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.client_read_response)
}
void Message::clear_client_read_response() {
  if (_internal_has_client_read_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.client_read_response_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_storage_pull_request(::proto::StoragePullRequest* storage_pull_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (storage_pull_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(storage_pull_request));
    if (message_arena != submessage_arena) {
      storage_pull_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, storage_pull_request, submessage_arena);
    }
    set_has_storage_pull_request();
    type_.storage_pull_request_ = storage_pull_request;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.storage_pull_request)
}
void Message::clear_storage_pull_request() {
  if (_internal_has_storage_pull_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.storage_pull_request_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_storage_pull_response(::proto::StoragePullResponse* storage_pull_response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (storage_pull_response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(storage_pull_response));
    if (message_arena != submessage_arena) {
      storage_pull_response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, storage_pull_response, submessage_arena);
    }
    set_has_storage_pull_response();
    type_.storage_pull_response_ = storage_pull_response;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.storage_pull_response)
}
void Message::clear_storage_pull_response() {
  if (_internal_has_storage_pull_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.storage_pull_response_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_storage_push_response(::proto::StoragePushResponse* storage_push_response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (storage_push_response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(storage_push_response));
    if (message_arena != submessage_arena) {
      storage_push_response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, storage_push_response, submessage_arena);
    }
    set_has_storage_push_response();
    type_.storage_push_response_ = storage_push_response;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.storage_push_response)
}
void Message::clear_storage_push_response() {
  if (_internal_has_storage_push_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.storage_push_response_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_raft_request(::proto::RaftRequest* raft_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (raft_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(raft_request));
    if (message_arena != submessage_arena) {
      raft_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, raft_request, submessage_arena);
    }
    set_has_raft_request();
    type_.raft_request_ = raft_request;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.raft_request)
}
void Message::clear_raft_request() {
  if (_internal_has_raft_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.raft_request_;
    }
    clear_has_type();
  }
}
void Message::set_allocated_raft_response(::proto::RaftResponse* raft_response) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_type();
  if (raft_response) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(raft_response));
    if (message_arena != submessage_arena) {
      raft_response = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, raft_response, submessage_arena);
    }
    set_has_raft_response();
    type_.raft_response_ = raft_response;
  }
  // @@protoc_insertion_point(field_set_allocated:proto.Message.raft_response)
}
void Message::clear_raft_response() {
  if (_internal_has_raft_response()) {
    if (GetArenaForAllocation() == nullptr) {
      delete type_.raft_response_;
    }
    clear_has_type();
  }
}
Message::Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:proto.Message)
}
Message::Message(const Message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_type();
  switch (from.type_case()) {
    case kTxn: {
      _internal_mutable_txn()->::proto::Transaction::MergeFrom(from._internal_txn());
      break;
    }
    case kReplyTxnResultToClient: {
      _internal_mutable_reply_txn_result_to_client()->::proto::ReplyTransactionToClient::MergeFrom(from._internal_reply_txn_result_to_client());
      break;
    }
    case kClientReadRequest: {
      _internal_mutable_client_read_request()->::proto::ClientReadRequest::MergeFrom(from._internal_client_read_request());
      break;
    }
    case kClientReadResponse: {
      _internal_mutable_client_read_response()->::proto::ClientReadResponse::MergeFrom(from._internal_client_read_response());
      break;
    }
    case kStoragePullRequest: {
      _internal_mutable_storage_pull_request()->::proto::StoragePullRequest::MergeFrom(from._internal_storage_pull_request());
      break;
    }
    case kStoragePullResponse: {
      _internal_mutable_storage_pull_response()->::proto::StoragePullResponse::MergeFrom(from._internal_storage_pull_response());
      break;
    }
    case kStoragePushResponse: {
      _internal_mutable_storage_push_response()->::proto::StoragePushResponse::MergeFrom(from._internal_storage_push_response());
      break;
    }
    case kRaftRequest: {
      _internal_mutable_raft_request()->::proto::RaftRequest::MergeFrom(from._internal_raft_request());
      break;
    }
    case kRaftResponse: {
      _internal_mutable_raft_response()->::proto::RaftResponse::MergeFrom(from._internal_raft_response());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:proto.Message)
}

inline void Message::SharedCtor() {
clear_has_type();
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:proto.Message)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_type()) {
    clear_type();
  }
}

void Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Message::clear_type() {
// @@protoc_insertion_point(one_of_clear_start:proto.Message)
  switch (type_case()) {
    case kTxn: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.txn_;
      }
      break;
    }
    case kReplyTxnResultToClient: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.reply_txn_result_to_client_;
      }
      break;
    }
    case kClientReadRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.client_read_request_;
      }
      break;
    }
    case kClientReadResponse: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.client_read_response_;
      }
      break;
    }
    case kStoragePullRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.storage_pull_request_;
      }
      break;
    }
    case kStoragePullResponse: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.storage_pull_response_;
      }
      break;
    }
    case kStoragePushResponse: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.storage_push_response_;
      }
      break;
    }
    case kRaftRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.raft_request_;
      }
      break;
    }
    case kRaftResponse: {
      if (GetArenaForAllocation() == nullptr) {
        delete type_.raft_response_;
      }
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = TYPE_NOT_SET;
}


void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Message)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_type();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Message::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .proto.Transaction txn = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_txn(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.ReplyTransactionToClient reply_txn_result_to_client = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_reply_txn_result_to_client(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.ClientReadRequest client_read_request = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_client_read_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.ClientReadResponse client_read_response = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_client_read_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.StoragePullRequest storage_pull_request = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_storage_pull_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.StoragePullResponse storage_pull_response = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_storage_pull_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.StoragePushResponse storage_push_response = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_storage_push_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.RaftRequest raft_request = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_raft_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .proto.RaftResponse raft_response = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_raft_response(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Message::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.Message)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .proto.Transaction txn = 1;
  if (_internal_has_txn()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::txn(this),
        _Internal::txn(this).GetCachedSize(), target, stream);
  }

  // .proto.ReplyTransactionToClient reply_txn_result_to_client = 2;
  if (_internal_has_reply_txn_result_to_client()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::reply_txn_result_to_client(this),
        _Internal::reply_txn_result_to_client(this).GetCachedSize(), target, stream);
  }

  // .proto.ClientReadRequest client_read_request = 3;
  if (_internal_has_client_read_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::client_read_request(this),
        _Internal::client_read_request(this).GetCachedSize(), target, stream);
  }

  // .proto.ClientReadResponse client_read_response = 4;
  if (_internal_has_client_read_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::client_read_response(this),
        _Internal::client_read_response(this).GetCachedSize(), target, stream);
  }

  // .proto.StoragePullRequest storage_pull_request = 5;
  if (_internal_has_storage_pull_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::storage_pull_request(this),
        _Internal::storage_pull_request(this).GetCachedSize(), target, stream);
  }

  // .proto.StoragePullResponse storage_pull_response = 6;
  if (_internal_has_storage_pull_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::storage_pull_response(this),
        _Internal::storage_pull_response(this).GetCachedSize(), target, stream);
  }

  // .proto.StoragePushResponse storage_push_response = 7;
  if (_internal_has_storage_push_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::storage_push_response(this),
        _Internal::storage_push_response(this).GetCachedSize(), target, stream);
  }

  // .proto.RaftRequest raft_request = 8;
  if (_internal_has_raft_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::raft_request(this),
        _Internal::raft_request(this).GetCachedSize(), target, stream);
  }

  // .proto.RaftResponse raft_response = 9;
  if (_internal_has_raft_response()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::raft_response(this),
        _Internal::raft_response(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Message)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (type_case()) {
    // .proto.Transaction txn = 1;
    case kTxn: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.txn_);
      break;
    }
    // .proto.ReplyTransactionToClient reply_txn_result_to_client = 2;
    case kReplyTxnResultToClient: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.reply_txn_result_to_client_);
      break;
    }
    // .proto.ClientReadRequest client_read_request = 3;
    case kClientReadRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.client_read_request_);
      break;
    }
    // .proto.ClientReadResponse client_read_response = 4;
    case kClientReadResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.client_read_response_);
      break;
    }
    // .proto.StoragePullRequest storage_pull_request = 5;
    case kStoragePullRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.storage_pull_request_);
      break;
    }
    // .proto.StoragePullResponse storage_pull_response = 6;
    case kStoragePullResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.storage_pull_response_);
      break;
    }
    // .proto.StoragePushResponse storage_push_response = 7;
    case kStoragePushResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.storage_push_response_);
      break;
    }
    // .proto.RaftRequest raft_request = 8;
    case kRaftRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.raft_request_);
      break;
    }
    // .proto.RaftResponse raft_response = 9;
    case kRaftResponse: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *type_.raft_response_);
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Message::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Message::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Message::GetClassData() const { return &_class_data_; }

void Message::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Message *>(to)->MergeFrom(
      static_cast<const Message &>(from));
}


void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Message)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.type_case()) {
    case kTxn: {
      _internal_mutable_txn()->::proto::Transaction::MergeFrom(from._internal_txn());
      break;
    }
    case kReplyTxnResultToClient: {
      _internal_mutable_reply_txn_result_to_client()->::proto::ReplyTransactionToClient::MergeFrom(from._internal_reply_txn_result_to_client());
      break;
    }
    case kClientReadRequest: {
      _internal_mutable_client_read_request()->::proto::ClientReadRequest::MergeFrom(from._internal_client_read_request());
      break;
    }
    case kClientReadResponse: {
      _internal_mutable_client_read_response()->::proto::ClientReadResponse::MergeFrom(from._internal_client_read_response());
      break;
    }
    case kStoragePullRequest: {
      _internal_mutable_storage_pull_request()->::proto::StoragePullRequest::MergeFrom(from._internal_storage_pull_request());
      break;
    }
    case kStoragePullResponse: {
      _internal_mutable_storage_pull_response()->::proto::StoragePullResponse::MergeFrom(from._internal_storage_pull_response());
      break;
    }
    case kStoragePushResponse: {
      _internal_mutable_storage_push_response()->::proto::StoragePushResponse::MergeFrom(from._internal_storage_push_response());
      break;
    }
    case kRaftRequest: {
      _internal_mutable_raft_request()->::proto::RaftRequest::MergeFrom(from._internal_raft_request());
      break;
    }
    case kRaftResponse: {
      _internal_mutable_raft_response()->::proto::RaftResponse::MergeFrom(from._internal_raft_response());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::InternalSwap(Message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(type_, other->type_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Message::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fmessage_2eproto_getter, &descriptor_table_proto_2fmessage_2eproto_once,
      file_level_metadata_proto_2fmessage_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::proto::Message*
Arena::CreateMaybeMessage< ::proto::Message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::proto::Message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
